import "./globals.css";
import {Inter} from "next/font/google";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex h-screen items-center justify-center ">
          <div className="m-auto max-w-screen-md flex-1 h-full max-h-96">
            <div className="h-full w-full rounded-3xl bg-white p-8 shadow-2xl text-white">
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
